include: package:flutter_lints/flutter.yaml
analyzer: 
  errors: 
    unused_import: warning
    avoid_print: warning

linter:
  rules:
    - avoid_print
    - avoid_empty_else
    - avoid_void_async
    - avoid_init_to_null
    - avoid_final_parameters
    - avoid_double_and_int_checks
    - avoid_field_initializers_in_const_classes
    - prefer_final_locals
    - prefer_single_quotes
    - file_names
    - empty_statements
    - unnecessary_const
    - annotate_overrides
    - one_member_abstracts
    - require_trailing_commas
    - empty_constructor_bodies
    - always_use_package_imports
    - lines_longer_than_80_chars
    - no_duplicate_case_values
    - depend_on_referenced_packages
    - use_named_constants
