name: oddshub
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  bloc: ^8.1.0
  bloc_test: ^9.1.1
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.0
  http: ^0.13.5
  intl: ^0.18.0

dev_dependencies:
  analyzer: 4.7.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lint: ^1.8.2
  mockito: ^5.3.2
  mocktail: ^0.3.0

flutter:
  assets:
    - assets/images/
    - assets/images/courses/
    - assets/images/registration/
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf
          weight: 400
