name: oddshub
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  bloc: ^8.1.0
  flutter_bloc: ^8.1.0
  equatable: ^2.0.5
  intl: ^0.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  analyzer: 4.7.0
  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  mocktail: ^0.3.0

flutter:
  assets: 
  - assets/images/
  uses-material-design: true
  fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/Noto_Sans/NotoSans-Regular.ttf
          weight: 400
